from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_SCRIPT = Path(__file__).parents[2] / "scripts" / "validate_public_docs_prose.py"
_SPEC = importlib.util.spec_from_file_location("validate_public_docs_prose", _SCRIPT)
assert _SPEC is not None and _SPEC.loader is not None
validator = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(validator)


@pytest.mark.parametrize(
    "markdown",
    (
        "# Title\n```text\nvalue — value\n```\n",
        "# Title\n~~~text\nvalue — value\n~~~\n",
        "# Title\n````markdown\n```\nvalue — value\n```\n````\n",
        "# Title\nUse ``flag ` with tick — value`` here.\n",
        "# Title\nUse ``a multiline\nvalue — value`` here.\n",
        "# Title\n```text\nDo not edit this file directly.\n```\n",
    ),
)
def test_code_is_excluded_from_prose_validation(markdown: str) -> None:
    assert validator.validation_errors(Path("doc.md"), markdown) == []


def test_visible_prose_is_still_validated() -> None:
    errors = validator.validation_errors(
        Path("doc.md"),
        "# Title\nDo not edit this file directly. A — B.\n",
    )

    assert any("generic public prose" in error for error in errors)
    assert any("em or en dash" in error for error in errors)
