"""Frozen, serializable domain values for the MCP Pal public SDK.

This module intentionally contains contracts and value objects only.  It does
not import application settings, FastAPI, Streamlit, pytest, SQLAlchemy, or
any process/transport implementation.
"""

# Used to resolve postponed public model annotations at runtime.
from collections.abc import Mapping as _Mapping  # noqa: F401
from datetime import datetime as _datetime  # noqa: F401
from typing import Any as _Any  # noqa: F401
from typing import Literal as _Literal  # noqa: F401

from ._types.base import (
    EVENT_SCHEMA_ID,
    EVENT_SCHEMA_VERSION,
    ActivityHealth,
    ArtifactId,
    ArtifactPolicy,
    AudioContent,
    CapabilityStatus,
    ConnectionId,
    ErrorCode,
    ErrorInfo,
    EvaluationId,
    EvaluationStatus,
    EventId,
    ExecutionId,
    ExecutionOutcome,
    ExecutionStatus,
    FileContent,
    FrozenModel,
    HarnessId,
    HarnessProfileId,
    Identifier,
    ImageContent,
    Metadata,
    OpaqueContent,
    ProjectId,
    ProtocolConstraint,
    ResourceLink,
    RevisionId,
    RevisionSelection,
    RunId,
    SecretReference,
    ServerId,
    ServerProfileId,
    SessionId,
    SuiteId,
    TextContent,
    TraceId,
    TransportKind,
    TrustLevel,
    TurnId,
    TurnOutcome,
    TurnStatus,
    WorkspaceKind,
)
from ._types.base import (
    _FrozenMapping as _FrozenMapping,
)
from ._types.evals import (
    EvaluationContext,
    EvaluationDecision,
    EvaluationRecord,
    EvaluationResult,
    EvaluationSource,
)
from ._types.events import (
    ArtifactRef,
    Event,
    EventDirection,
    EventKind,
    EventOrigin,
    EventSource,
    EvidenceRef,
    JsonRpcId,
    LifecyclePhase,
    PayloadRef,
    ReasoningState,
    ReasoningVisibility,
    RequestLink,
    TraceResult,
)
from ._types.results import (
    CallToolResult,
    Capability,
    DirectResult,
    ExecutionEvidence,
    ExecutionReport,
    ExecutionResult,
    GetPromptResult,
    ListPromptsResult,
    ListResourcesResult,
    ListTemplatesResult,
    ListToolsResult,
    PingResult,
    PromptInfo,
    Readiness,
    ReadResourceResult,
    ResourceInfo,
    TemplateInfo,
    ToolInfo,
    TurnResponse,
    TurnResult,
)
from ._types.specs import (
    ACPAgent,
    AgentSpec,
    CallTool,
    ClaudeCode,
    Codex,
    ContentBlock,
    DirectOperation,
    DirectSpec,
    ElicitationPolicy,
    EvaluationRegistration,
    ExecutionSpec,
    FilesystemPolicy,
    FullToolPolicy,
    GetPrompt,
    HarnessProfileRef,
    HarnessSpec,
    HarnessValue,
    HTTPServer,
    InProcessServer,
    ListPrompts,
    ListResources,
    ListTemplates,
    ListTools,
    NativeToolPolicy,
    OpenCode,
    PermissionPolicy,
    Pi,
    Ping,
    ReadResource,
    RestrictiveToolPolicy,
    SamplingPolicy,
    ServerBinding,
    ServerDefinition,
    ServerProfileRef,
    ServerValue,
    SessionForkRequest,
    SessionSource,
    SSEServer,
    StdioServer,
    TerminalPolicy,
    ToolPolicy,
    UserMessage,
    WorkspacePolicy,
)
from ._types.state import (
    ExecutionPage,
    ExecutionState,
    TurnState,
)

__all__ = [  # noqa: RUF022 - public API order is compatibility-checked
    "EVENT_SCHEMA_ID",
    "EVENT_SCHEMA_VERSION",
    "ACPAgent",
    "ActivityHealth",
    "AgentSpec",
    "ArtifactId",
    "ArtifactPolicy",
    "ArtifactRef",
    "AudioContent",
    "Event",
    "Capability",
    "CapabilityStatus",
    "ClaudeCode",
    "Codex",
    "Pi",
    "ConnectionId",
    "ContentBlock",
    "DirectSpec",
    "DirectOperation",
    "ToolInfo",
    "ResourceInfo",
    "TemplateInfo",
    "PromptInfo",
    "ElicitationPolicy",
    "ErrorCode",
    "ErrorInfo",
    "EventDirection",
    "EventKind",
    "EventOrigin",
    "PayloadRef",
    "EventSource",
    "EvaluationContext",
    "EvaluationDecision",
    "EvaluationId",
    "EvaluationSource",
    "EvaluationRegistration",
    "EvaluationResult",
    "EvaluationStatus",
    "EvaluationRecord",
    "RunId",
    "SuiteId",
    "EventId",
    "ExecutionId",
    "ExecutionEvidence",
    "ExecutionOutcome",
    "ExecutionPage",
    "ExecutionResult",
    "ExecutionState",
    "ProjectId",
    "ExecutionSpec",
    "FileContent",
    "FilesystemPolicy",
    "FrozenModel",
    "FullToolPolicy",
    "HarnessId",
    "HarnessProfileId",
    "HarnessProfileRef",
    "HarnessSpec",
    "HarnessValue",
    "Identifier",
    "ImageContent",
    "InProcessServer",
    "ExecutionStatus",
    "JsonRpcId",
    "LifecyclePhase",
    "Metadata",
    "NativeToolPolicy",
    "OpaqueContent",
    "OpenCode",
    "PermissionPolicy",
    "ProtocolConstraint",
    "Readiness",
    "ResourceLink",
    "RevisionId",
    "RevisionSelection",
    "RestrictiveToolPolicy",
    "SSEServer",
    "SamplingPolicy",
    "SecretReference",
    "ServerBinding",
    "ServerDefinition",
    "ServerId",
    "ServerProfileId",
    "ServerProfileRef",
    "ServerValue",
    "SessionForkRequest",
    "SessionId",
    "SessionSource",
    "ExecutionReport",
    "EvidenceRef",
    "ReasoningState",
    "ReasoningVisibility",
    "RequestLink",
    "StdioServer",
    "HTTPServer",
    "TerminalPolicy",
    "TextContent",
    "TraceId",
    "TraceResult",
    "ToolPolicy",
    "TransportKind",
    "TrustLevel",
    "TurnId",
    "TurnStatus",
    "TurnOutcome",
    "TurnResponse",
    "TurnResult",
    "TurnState",
    "UserMessage",
    "WorkspaceKind",
    "WorkspacePolicy",
    "ListTools",
    "ListResources",
    "ListTemplates",
    "ListPrompts",
    "CallTool",
    "ReadResource",
    "GetPrompt",
    "Ping",
    "DirectResult",
    "ListToolsResult",
    "ListResourcesResult",
    "ListTemplatesResult",
    "ListPromptsResult",
    "CallToolResult",
    "ReadResourceResult",
    "GetPromptResult",
    "PingResult",
]


# Keep legacy classes importable while reducing wildcard exports to the focused
# value surface.  Explicit imports continue to resolve through module globals.
_COMPAT_EXPORTS = tuple(__all__)
# This order is a compatibility contract for the focused wildcard surface.
__all__ = [  # noqa: RUF022
    "EVENT_SCHEMA_ID",
    "EVENT_SCHEMA_VERSION",
    "ExecutionOutcome",
    "ExecutionResult",
    "TurnOutcome",
    "TurnResult",
    "HTTPServer",
    "SSEServer",
    "StdioServer",
    "InProcessServer",
    "SecretReference",
    "ServerBinding",
    "ServerValue",
    "ToolPolicy",
    "UserMessage",
    "TextContent",
    "DirectSpec",
    "DirectOperation",
    "CallTool",
    "ListTools",
    "ListResources",
    "ListTemplates",
    "ListPrompts",
    "ReadResource",
    "GetPrompt",
    "Ping",
    "EvaluationResult",
    "EvaluationRecord",
    "EvaluationContext",
    "EvaluationDecision",
    "EvaluationStatus",
    "EvaluationSource",
    "TraceResult",
    "EvidenceRef",
    "ArtifactRef",
    "ExecutionReport",
    "ExecutionEvidence",
    "Capability",
    "Readiness",
    "ProtocolConstraint",
    "WorkspacePolicy",
    "PermissionPolicy",
    "ElicitationPolicy",
    "SamplingPolicy",
    "FilesystemPolicy",
    "TerminalPolicy",
]

# Keep public model metadata and pickle paths stable after moving definitions.
for _name in _COMPAT_EXPORTS:
    _value = globals().get(_name)
    if isinstance(_value, type) and _value.__module__.startswith("mcp_pal._types"):
        _value.__module__ = __name__
_FrozenMapping.__module__ = __name__
del _name, _value
