#!/usr/bin/env python3
"""Validate low-noise prose rules across external M3 documentation."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "docs" / "site"
EXTERNAL_DOCUMENTS = (
    ROOT / "README.md",
    ROOT / "app" / "README.md",
    ROOT / "app" / "docs" / "api-v2.md",
    ROOT / "cli" / "README.md",
    ROOT / "sdk" / "README.md",
)
SDK_REDIRECTS = ROOT / "sdk" / "docs"

FORBIDDEN_TEXT = (
    "Stored and validated as part of this public value.",
    "Public method on `",
    "Public class in `",
    "Public callable in `",
    "Do not edit this file directly.",
)
STAGED_OPENING = re.compile(
    r"^(?:Of course!|Certainly!|Great question!|I hope this helps\b|"
    r"Let's (?:dive|explore|break this down)\b|Here's what you need to know\b|"
    r"Here's the thing\b|The thing is\b|Without further ado\b)",
    re.IGNORECASE,
)
BOLD_LABEL = re.compile(r"^\s*\*\*[^*]+:\*\*")


def public_documents() -> tuple[Path, ...]:
    paths = {
        *SITE.rglob("*.md"),
        *SDK_REDIRECTS.glob("*.md"),
        *EXTERNAL_DOCUMENTS,
    }
    return tuple(sorted(paths))


def visible_lines(text: str) -> list[tuple[int, str]]:
    lines: list[tuple[int, str]] = []
    in_fence = False
    for number, line in enumerate(text.splitlines(), start=1):
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        without_code = re.sub(r"`[^`]*`", "", line)
        lines.append((number, without_code))
    return lines


def main() -> int:
    errors: list[str] = []
    paths = public_documents()
    for path in paths:
        relative = path.relative_to(ROOT)
        text = path.read_text(encoding="utf-8")
        lines = visible_lines(text)
        headings = [number for number, line in lines if re.match(r"^#\s+", line)]
        if len(headings) != 1:
            errors.append(f"{relative}: expected exactly one H1, found {len(headings)}")
        for forbidden in FORBIDDEN_TEXT:
            if forbidden in text:
                errors.append(f"{relative}: contains generic public prose: {forbidden}")
        for number, line in lines:
            if "\u2014" in line or "\u2013" in line:
                errors.append(f"{relative}:{number}: prose contains an em or en dash")
            if BOLD_LABEL.match(line):
                errors.append(
                    f"{relative}:{number}: prose starts with a decorative bold label"
                )
            if STAGED_OPENING.match(line.strip()):
                errors.append(f"{relative}:{number}: prose starts with staged wording")
    if errors:
        print("Public documentation prose validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print(f"Validated prose in {len(paths)} public documentation files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
